In [1]:
x =[1,2,3]
y = x

In [2]:
y[1] = 5
y


[1, 5, 3]

In [3]:
x

[1, 5, 3]

In [4]:
import numpy as np

np_x = np.array(x)
np_x

array([1, 5, 3])

In [5]:
np_x.shape


(3,)

In [6]:
np_x.ndim

1

In [7]:
?np_x

In [8]:
dir(np_x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [9]:
x

[1, 5, 3]

In [10]:
np_x *= 3
np_x

array([ 3, 15,  9])

In [11]:
np_y = np_x
np_y

array([ 3, 15,  9])

In [12]:
np_y[2] = 10
np_x, type(np_x)

(array([ 3, 15, 10]), numpy.ndarray)

In [13]:
x = np.linspace(1,500,100)
x

array([  1.        ,   6.04040404,  11.08080808,  16.12121212,
        21.16161616,  26.2020202 ,  31.24242424,  36.28282828,
        41.32323232,  46.36363636,  51.4040404 ,  56.44444444,
        61.48484848,  66.52525253,  71.56565657,  76.60606061,
        81.64646465,  86.68686869,  91.72727273,  96.76767677,
       101.80808081, 106.84848485, 111.88888889, 116.92929293,
       121.96969697, 127.01010101, 132.05050505, 137.09090909,
       142.13131313, 147.17171717, 152.21212121, 157.25252525,
       162.29292929, 167.33333333, 172.37373737, 177.41414141,
       182.45454545, 187.49494949, 192.53535354, 197.57575758,
       202.61616162, 207.65656566, 212.6969697 , 217.73737374,
       222.77777778, 227.81818182, 232.85858586, 237.8989899 ,
       242.93939394, 247.97979798, 253.02020202, 258.06060606,
       263.1010101 , 268.14141414, 273.18181818, 278.22222222,
       283.26262626, 288.3030303 , 293.34343434, 298.38383838,
       303.42424242, 308.46464646, 313.50505051, 318.54

In [14]:
type(x)


numpy.ndarray

In [15]:
x.ndim

1

In [16]:
x.shape

(100,)

In [17]:
x.size, len(x)

(100, 100)

In [18]:
x.dtype

dtype('float64')

In [19]:
x = x.round(1)

In [20]:
x = x.reshape(20,5)
x

array([[  1. ,   6. ,  11.1,  16.1,  21.2],
       [ 26.2,  31.2,  36.3,  41.3,  46.4],
       [ 51.4,  56.4,  61.5,  66.5,  71.6],
       [ 76.6,  81.6,  86.7,  91.7,  96.8],
       [101.8, 106.8, 111.9, 116.9, 122. ],
       [127. , 132.1, 137.1, 142.1, 147.2],
       [152.2, 157.3, 162.3, 167.3, 172.4],
       [177.4, 182.5, 187.5, 192.5, 197.6],
       [202.6, 207.7, 212.7, 217.7, 222.8],
       [227.8, 232.9, 237.9, 242.9, 248. ],
       [253. , 258.1, 263.1, 268.1, 273.2],
       [278.2, 283.3, 288.3, 293.3, 298.4],
       [303.4, 308.5, 313.5, 318.5, 323.6],
       [328.6, 333.7, 338.7, 343.7, 348.8],
       [353.8, 358.9, 363.9, 368.9, 374. ],
       [379. , 384.1, 389.1, 394.2, 399.2],
       [404.2, 409.3, 414.3, 419.4, 424.4],
       [429.4, 434.5, 439.5, 444.6, 449.6],
       [454.6, 459.7, 464.7, 469.8, 474.8],
       [479.8, 484.9, 489.9, 495. , 500. ]])

In [21]:
x.ndim

2

In [22]:
x[1]

array([26.2, 31.2, 36.3, 41.3, 46.4])

In [23]:
x[4:,2:]

array([[111.9, 116.9, 122. ],
       [137.1, 142.1, 147.2],
       [162.3, 167.3, 172.4],
       [187.5, 192.5, 197.6],
       [212.7, 217.7, 222.8],
       [237.9, 242.9, 248. ],
       [263.1, 268.1, 273.2],
       [288.3, 293.3, 298.4],
       [313.5, 318.5, 323.6],
       [338.7, 343.7, 348.8],
       [363.9, 368.9, 374. ],
       [389.1, 394.2, 399.2],
       [414.3, 419.4, 424.4],
       [439.5, 444.6, 449.6],
       [464.7, 469.8, 474.8],
       [489.9, 495. , 500. ]])

## 06/29/2022

In [24]:
import numpy as np

In [129]:
heights = [175, 148, 165]
np_heights = np.array(heights)

In [26]:
type(np_heights)
np_heights.size

3

In [27]:
len(np_heights)

3

In [28]:
np_heights.ndim

1

In [29]:
np_heights.dtype

dtype('int32')

In [30]:
np_heights.itemsize

4

In [31]:
?np_heights.astype

In [130]:
np_heights.astype(float, copy = False)

array([175., 148., 165.])

In [33]:
np_heights.dtype

dtype('int32')

In [131]:
np_weights = np.array([195.0, 110.0, 100.0,]) 
type(np_weights), np_weights

(numpy.ndarray, array([195., 110., 100.]))

In [35]:
np.size(np_weights)

3

In [36]:
np_weights.ndim

1

In [37]:
np_weights.dtype

dtype('float64')

In [38]:
np_names = np.array(['Michael', 'Angela', 'Edward'])


In [132]:
np_weights_kg = np_weights*0.453592
np_weights_kg

array([88.45044, 49.89512, 45.3592 ])

In [133]:
np_heights_m = np_heights/100
np_heights_m

array([1.75, 1.48, 1.65])

In [134]:
bmi = np_weights_kg/np_heights_m**2

In [135]:
bmi

array([28.88177633, 22.77899927, 16.66086318])

BMI Categories:
- Underweight = <18.5
* Normal weight = 18.5–24.9
- Overweight = 25–29.9
- Obesity = BMI of 30 or greater

In [56]:
bmi[:2]

array([28.88177633, 18.35154302])

In [60]:
underweight = bmi < 18.5
bmi[underweight]

array([18.35154302, 16.66086318])

In [65]:
bmi[[True, False, False]]

array([28.88177633])

In [138]:
mean = bmi.sum()/bmi.size
mean

22.773879591099078

In [136]:
bmi_mean = bmi.mean()


In [137]:
np.mean(bmi)

22.773879591099078

In [139]:
np.median(bmi)

22.77899926953981

In [142]:
bmi_std = bmi.std()
bmi_std

4.989168214511453

In [82]:
bmi.var()

29.232769998783326

In [93]:
d = np.arange(10,25,5)
d.shape

(3,)

In [89]:
d

array([10, 15, 20])

In [98]:
e = np.linspace(0,2,9)
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [99]:
?np.linspace

In [101]:
?np.full

In [103]:
f = np.full((2,2),7)
f

array([[7, 7],
       [7, 7]])

In [106]:
c = np.empty([3,2])
c.itemsize

8

In [107]:
a = np.zeros([3,2])
a.itemsize

8

In [113]:
?np.random.normal

In [141]:
b = np.random.normal(bmi_mean, bmi_std, 100 )

b

array([21.71815878, 22.03886202, 18.10186098, 18.33095002, 11.6201538 ,
       22.26277263, 20.25232842, 15.2550189 , 25.47858291, 27.04018853,
       23.78781279, 27.35405806, 30.76319523, 23.69544347, 10.76253418,
       24.3627537 , 24.00937181, 19.35182624, 24.88335204, 20.86886042,
       22.48572552, 20.30633134, 19.7849572 , 27.75308201, 23.95966014,
       23.32817103, 20.27738957, 19.76816295, 23.33771209, 26.97648457,
       22.97988571, 27.74811086, 18.42178399, 21.91115031, 24.74108262,
       20.32092166, 19.27366508, 23.29437853, 18.95417678, 23.97413876,
       21.38902583, 25.09291281, 22.11534088, 24.01636047, 12.59814916,
       13.71071238, 22.16738698, 25.88855756, 22.82955025, 31.19283685,
       24.39129131, 21.41009291, 16.866571  , 23.64367538, 22.13689091,
       15.39677732, 18.54273928, 21.51484222, 26.10033645, 23.29530426,
       24.9015341 , 22.96394159, 14.01854339, 26.05928457, 21.42185134,
       19.63702681, 18.94827676, 26.31276219, 27.73310246, 22.37

In [143]:
b.std()

4.2957539667916365

In [144]:
z = np.random.choice(np_names, 10)
z

array(['Michael', 'Edward', 'Michael', 'Michael', 'Edward', 'Edward',
       'Edward', 'Angela', 'Angela', 'Edward'], dtype='<U7')