# Chapter 2 -- Create Numpy Arrays

## 2-1 Create arrays from Python structures

### Create NumPy arrays using Python's "array like" data types


In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.18.1


In [3]:
my_list = [-17, 0, 4, 5, 9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [4]:
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [8]:
my_tuple = (14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

### Difference between python and numpy data structures

In [6]:
my_tuple * 6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [7]:
np.array(my_tuple) * 6

array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])

## 2-2 Intrinsic NumPy array creation using NumPy's methods

In [ ]:
import numpy as np


In [9]:
arange(7)

NameError: name 'arange' is not defined

In [10]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [11]:
np.arange(10, 23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [12]:
np.arange(10, 23) - 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
len(np.arange(10, 23))

13

In [16]:
my_range_array = np.arange(10, 23)

my_range_array.size

13

In [17]:
np.arange(10, 23).size

13

In [18]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [22]:
np.arange(10, 26, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(26, step = 5) 
# The start value is optional, If not specified, the default sart value is 0

array([ 0,  5, 10, 15, 20, 25])

In [25]:
np.arange(0, 26, step=5)

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
np.arange(0, 26, 5)

## 2-3 `linspace()`, `zeros()`, `ones()`, and NumPy data types

In [26]:
np.linspace(5, 15, 9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [28]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [30]:
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [31]:
# return "step"
my_linspace[1]

1.25

In [32]:
np.linspace(5, 15, 9, retstep=True)[1]

1.25

### `zeros()`

In [37]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((5,4)) # shpe is int or tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.zeros((5, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### `np.ones()`

In [40]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.ones((5, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### Numpy data types: `dtype`

In [45]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros(11).dtype

dtype('float64')

In [44]:
np.zeros(11, dtype = 'int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [48]:
np.zeros(11, dtype = 'int64').dtype

dtype('int64')

In [49]:
np.zeros(11, dtype = np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)